#!/bin/bash

# Perform these steps, the last of which will run this script:
# install Xcode and updates
# create non-admin user
# customize system preferences
# install browsers and security extensions
# set login photo
# install racket
# install xquartz
# install homebrew; brew doctor
# ssh-keygen -t rsa -b 4096 -C "user@hostname"
# cd && git clone git@github.com:gregr/config.git && cd config && ./install-osx

here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

"$here/pack/manage.py" --install
git submodule update --init

cat > ~/.bash_profile << PROFILECONTENTS
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
if [ -f /usr/local/Library/Contributions/brew_bash_completion.sh ]; then
  source /usr/local/Library/Contributions/brew_bash_completion.sh
fi
PROFILECONTENTS

sudo easy_install pip
sudo pip install ansible
while read package; do
  sudo pip install "$package"
done < "$here/PIP-PACKAGES"

brew update
while read package; do
  brew install "$package"
done < "$here/BREW-PRIMARY-PACKAGES"
while read package; do
  brew install "$package"
done < "$here/BREW-PACKAGES"

cabal update
while read package; do
  cabal install "$package"
done < "$here/CABAL-PACKAGES"
