#!/bin/bash

# Perform these steps, the last of which will run this script:
# install Xcode and updates
# create non-admin user
# customize system preferences
# install browsers and security extensions
# set login photo
# install homebrew; brew doctor
# ssh-keygen -t rsa -b 4096 -C "user@hostname"
# cd && git clone git@github.com:gregr/config.git && cd config && ./install-osx

here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

"$here/dotfiles/manage.py" --install
git submodule update --init

cat > ~/.bash_profile << PROFILECONTENTS
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
if [ -f /usr/local/Library/Contributions/brew_bash_completion.sh ]; then
  source /usr/local/Library/Contributions/brew_bash_completion.sh
fi
if [ -d "$HOME/bin" ]; then
  PATH="$HOME/bin:$PATH"
fi
PROFILECONTENTS

brew install bash && sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells' && chsh -s /usr/local/bin/bash

brew install python
pip install --upgrade pip setuptools
pip install ansible
while read package; do
  pip install "$package"
done < "$here/PIP-PACKAGES"

brew update
while read package; do
  brew install "$package"
done < "$here/BREW-PRIMARY-PACKAGES"
while read package; do
  brew install "$package"
done < "$here/BREW-PACKAGES"
