(setq inhibit-splash-screen t)
(custom-set-variables '(load-home-init-file t t))
(menu-bar-mode 0)
(column-number-mode t)
(iswitchb-mode t)
(global-auto-revert-mode t)
(setq-default case-fold-search t)
(setq-default indent-tabs-mode nil)
(setq vc-handled-backends nil)
(setq backup-directory-alist (quote ((".*" . "~/.backup"))))
(setq-default visible-bell t)
(setq-default bell-inhibit-time 10)
(global-font-lock-mode t)
(transient-mark-mode t)
(show-paren-mode t)
(setq show-paren-style 'mixed)
(setq truncate-partial-width-windows nil)
(set-face-background 'trailing-whitespace "#900000")
(setq-default show-trailing-whitespace t)
(if (fboundp 'delete-trailing-whitespace)
    (add-hook 'write-file-hooks 'delete-trailing-whitespace))
(set-foreground-color "#dbdbdb")
(set-background-color "#000000")
(custom-set-faces
 '(font-lock-comment-face ((t (:foreground "cyan")))))
;(setq scroll-step 1)

(mouse-wheel-mode t)
(setq x-select-enable-clipboard t)
(global-set-key "\C-y" 'clipboard-yank)
(global-set-key "\C-w" 'clipboard-kill-region)
(global-set-key "\M-w" 'clipboard-kill-ring-save)

(global-set-key "\M-g"  'goto-line)
(global-set-key "\C-q"  'undo)
(global-set-key "\C-o"  'other-window)

(defun indent-all ()
  (interactive)
  (indent-region (point-min) (point-max) nil))
(defun smart-split ()
  (interactive)
  (defun smart-split-helper (w)
    (if (> (window-width w) (* 2 81))
    (let ((w2 (split-window w 82 t)))
      (smart-split-helper w2))))
  (smart-split-helper nil))
(defun set-window-width (n)
  (adjust-window-trailing-edge (selected-window) (- n (window-width)) t))
(defun set-80-columns ()
  (interactive)
  (set-window-width 81)) ; 1 more for padding
